### ISSUE TITLE
Write a README for this lab

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/3601-lab4_mongo#1]

**Comment by joethe** [comment]
We'll want remember to include some helpful links to mongo's JDBC documentation.

**Comment by joethe** [comment]
In general, the resources section of the readme needs to be updated.

- JDBC documentation
- Mongo Shell documentation
- Morphia documentation ???

**Comment by joethe** [comment]
We should also add information on how to read some of the more common errors associated with using Mongo.

**Comment by NicMcPhee** [comment]
After looking at things some, I’m going to, for now, skip doing an example of Morphia or MongoJack as ways to convert BSON to POJOs. As far as I can tell, all these tools provide *way* more than just translation; they essentially wrap the whole Mongo business, giving you new search tools, etc., etc. If part of our goal this semester is to reduce the “magic”, all these seem to introduce rather a lot of “magic”, so my inclination is to stick with “plain” Mongo so students can wrap their head round the basics of Mongo before we/they obscure that with some additional layers.

**Comment by joethe** [comment]
Sounds good. Guess this is "done" for S17.
